# name is made short because the check path becomes really long and repeditive
name: run

on:
  workflow_call:
    inputs:
      solutionName:
        required: true
        type: string

jobs:
  omd-generation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        path: a

    - name: Checkout dpvreony/github-action-workflow
      uses: actions/checkout@064fe7f3312418007dea2b49a19844a9ee378f49
      with:
        repository: dpvreony/github-action-workflows
        path: github-action-workflows

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: "github-action-workflows/eng/omd/global.json"
        
    - name: Install dotnet tools
      run: dotnet tool restore --tool-manifest dotnet-tools.json
      working-directory:
        github-action-workflows/eng/omd

    - name: Prepare Artifact Directory
      run: |
        mkdir -p artifacts/omd

    - name: Generate OMD HTML
      run: |
        dotnet generateomd /source=${{ github.workspace }}/a/src /output=${{ github.workspace }}/artifacts/omd/index.htm /format=html
      working-directory: 
         github-action-workflows/eng/omd

    - name: store omd
      if: ${{ always() }}
      uses: actions/upload-artifact@v6
      with:
        name: omd
        path: artifacts/omd
